In [1]:
import numpy as np
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten, Embedding 

## 단어 토큰화

In [2]:
# 케라스의 텍스트 전처리와 관련한 함수중 text_to_word_sequence 함수를 불러오기
from tensorflow.keras.preprocessing.text import text_to_word_sequence

# 전처리 할 텍스트 지정
text='꿈이 있으면 휴식은 사치일 뿐'

# 해당 텍스트 토큰화
result = text_to_word_sequence(text)
print(text)
print(result)

꿈이 있으면 휴식은 사치일 뿐
['꿈이', '있으면', '휴식은', '사치일', '뿐']


In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer
# 단어 빈도수 세기

# 세 개의 문장 정의
docs=['공부는 공부를 하기 위해서가 아닌 문제를 해결하기 위해서 해야 합니다',
    '해결하려는 문제가 나와 관련된 문제일수록 더욱 노력하게 됩니다',
    '더 많은 공부보단 다양한 경험을 하면서 자신이 할 수 있는 한계점을 찾고 해결하기 위해 노력합시다']

# 토큰화 함수를 이용해 전처리 하는 과정
token=Tokenizer()           # 토큰화 함수 지정
token.fit_on_texts(docs)    # 토큰화 함수에 문장 적용

# 각 단어 빈도수
print(token.word_counts)

OrderedDict([('공부는', 1), ('공부를', 1), ('하기', 1), ('위해서가', 1), ('아닌', 1), ('문제를', 1), ('해결하기', 2), ('위해서', 1), ('해야', 1), ('합니다', 1), ('해결하려는', 1), ('문제가', 1), ('나와', 1), ('관련된', 1), ('문제일수록', 1), ('더욱', 1), ('노력하게', 1), ('됩니다', 1), ('더', 1), ('많은', 1), ('공부보단', 1), ('다양한', 1), ('경험을', 1), ('하면서', 1), ('자신이', 1), ('할', 1), ('수', 1), ('있는', 1), ('한계점을', 1), ('찾고', 1), ('위해', 1), ('노력합시다', 1)])


In [4]:
# 각 단어 빈도수
print(token.word_counts)

OrderedDict([('공부는', 1), ('공부를', 1), ('하기', 1), ('위해서가', 1), ('아닌', 1), ('문제를', 1), ('해결하기', 2), ('위해서', 1), ('해야', 1), ('합니다', 1), ('해결하려는', 1), ('문제가', 1), ('나와', 1), ('관련된', 1), ('문제일수록', 1), ('더욱', 1), ('노력하게', 1), ('됩니다', 1), ('더', 1), ('많은', 1), ('공부보단', 1), ('다양한', 1), ('경험을', 1), ('하면서', 1), ('자신이', 1), ('할', 1), ('수', 1), ('있는', 1), ('한계점을', 1), ('찾고', 1), ('위해', 1), ('노력합시다', 1)])


In [5]:
# 총 문장 수
token.document_count

3

In [6]:
# 각 단어가 몇개의 문장에 포함되어 있는가
print(token.word_docs)

defaultdict(<class 'int'>, {'아닌': 1, '문제를': 1, '위해서': 1, '해야': 1, '공부를': 1, '위해서가': 1, '공부는': 1, '하기': 1, '해결하기': 2, '합니다': 1, '관련된': 1, '해결하려는': 1, '나와': 1, '문제일수록': 1, '더욱': 1, '문제가': 1, '노력하게': 1, '됩니다': 1, '다양한': 1, '자신이': 1, '경험을': 1, '수': 1, '찾고': 1, '하면서': 1, '있는': 1, '더': 1, '노력합시다': 1, '한계점을': 1, '할': 1, '많은': 1, '공부보단': 1, '위해': 1})


In [7]:
# 각 단어의 매겨진 인덱스 값
print(token.word_index)

{'해결하기': 1, '공부는': 2, '공부를': 3, '하기': 4, '위해서가': 5, '아닌': 6, '문제를': 7, '위해서': 8, '해야': 9, '합니다': 10, '해결하려는': 11, '문제가': 12, '나와': 13, '관련된': 14, '문제일수록': 15, '더욱': 16, '노력하게': 17, '됩니다': 18, '더': 19, '많은': 20, '공부보단': 21, '다양한': 22, '경험을': 23, '하면서': 24, '자신이': 25, '할': 26, '수': 27, '있는': 28, '한계점을': 29, '찾고': 30, '위해': 31, '노력합시다': 32}


In [8]:
# 문장 별 토큰화 확인
x=token.texts_to_sequences(docs)
print(x)

[[2, 3, 4, 5, 6, 7, 1, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18], [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 1, 31, 32]]


## 리뷰 감성분석

In [9]:
# 텍스트 리뷰 10개를 정의합니다.
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","글쎄요 재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [10]:
token=Tokenizer()
token.fit_on_texts(docs)

token

In [11]:
# 단어별 빈도수 계산
print(token.word_counts)

OrderedDict([('너무', 1), ('재밌네요', 1), ('최고예요', 1), ('참', 1), ('잘', 1), ('만든', 1), ('영화예요', 1), ('추천하고', 1), ('싶은', 1), ('영화입니다', 1), ('한번', 1), ('더', 1), ('보고싶네요', 1), ('글쎄요', 2), ('별로예요', 1), ('생각보다', 1), ('지루하네요', 1), ('연기가', 1), ('어색해요', 1), ('재미없어요', 1)])


In [12]:
# 각 단어의 인덱스
print(token.word_index)

{'글쎄요': 1, '너무': 2, '재밌네요': 3, '최고예요': 4, '참': 5, '잘': 6, '만든': 7, '영화예요': 8, '추천하고': 9, '싶은': 10, '영화입니다': 11, '한번': 12, '더': 13, '보고싶네요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [13]:
# 문장 별 토큰화 확인
x=token.texts_to_sequences(docs)
print(x)

[[2, 3], [4], [5, 6, 7, 8], [9, 10, 11], [12, 13, 14], [1], [15], [16, 17], [18, 19], [1, 20]]


In [14]:
# 문장 최대 길이 확인
len_list=[]
for i in range(len(x)):
    len_list.append(len(x[i]))

print("문장 별 길이:", len_list)
print("문장 최대 길이:", np.max(len_list))

문장 별 길이: [2, 1, 4, 3, 3, 1, 1, 2, 2, 2]
문장 최대 길이: 4


In [15]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
# 패딩: 서로 다른 길이의 데이터를 4로 맞추어 줍니다
padded_x=pad_sequences(x)
print('패딩 결과\n', padded_x)

패딩 결과
 [[ 0  0  2  3]
 [ 0  0  0  4]
 [ 5  6  7  8]
 [ 0  9 10 11]
 [ 0 12 13 14]
 [ 0  0  0  1]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  1 20]]


테스트 데이터 만들기

In [16]:
test_docs = ["영화 재밌네요","올해 영화 중 최고예요","참 잘 만든 영화예요","추천하고 싶지 않은 영화입니다","두번 더 보고싶네요","글쎄요","아주 별로예요","생각보다 재미없네요","배우 연기가 어색해요","글쎄요 재미없어요"]
classes_test = array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0])

In [17]:
token_test=Tokenizer()
token_test.fit_on_texts(test_docs)
token_test

In [18]:
print(token_test.word_index)

{'영화': 1, '글쎄요': 2, '재밌네요': 3, '올해': 4, '중': 5, '최고예요': 6, '참': 7, '잘': 8, '만든': 9, '영화예요': 10, '추천하고': 11, '싶지': 12, '않은': 13, '영화입니다': 14, '두번': 15, '더': 16, '보고싶네요': 17, '아주': 18, '별로예요': 19, '생각보다': 20, '재미없네요': 21, '배우': 22, '연기가': 23, '어색해요': 24, '재미없어요': 25}


In [19]:
# 문장 별 토큰화 결과 확인
test_x = token_test.texts_to_sequences(test_docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  test_x)


리뷰 텍스트, 토큰화 결과:
 [[1, 3], [4, 1, 5, 6], [7, 8, 9, 10], [11, 12, 13, 14], [15, 16, 17], [2], [18, 19], [20, 21], [22, 23, 24], [2, 25]]


In [20]:
test_padded_x = pad_sequences(test_x, 4)  
print("\n패딩 결과:\n", test_padded_x) 


패딩 결과:
 [[ 0  0  1  3]
 [ 4  1  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [ 0 15 16 17]
 [ 0  0  0  2]
 [ 0  0 18 19]
 [ 0  0 20 21]
 [ 0 22 23 24]
 [ 0  0  2 25]]


## 딥 러닝 모델

In [21]:
# 임베딩에 입려될 단어의 수를 지정합니다. (패딩 0까지 단어로 포함하기 위해 1을 더한다)
word_size=len(token.word_index)+1
word_size

21

In [22]:
# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()

# 임베딩 층 입력 벡터 크기: 단어 인덱스 수(21), 출력 벡터 크기: 10(수정 가능), 뉴스 패딩 결과인 4개씩 단어 입력
model.add(Embedding(21,10,input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid')) # 이진 분류

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [23]:
model.fit(padded_x, classes, epochs=20)

Epoch 1/20
1/1 [==============================] - 0s 327ms/step - loss: 0.6972 - accuracy: 0.6000
Epoch 2/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6950 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6929 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6908 - accuracy: 0.6000
Epoch 5/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6887 - accuracy: 0.6000
Epoch 6/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6866 - accuracy: 0.6000
Epoch 7/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6845 - accuracy: 0.7000
Epoch 8/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6825 - accuracy: 0.8000
Epoch 9/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6804 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6783 - accuracy: 0.8000
Epoch 11/20
1/1 [====================

In [24]:
model.evaluate(padded_x, classes)

1/1 [==============================] - 0s 124ms/step - loss: 0.6556 - accuracy: 0.9000


[0.6556402444839478, 0.8999999761581421]

In [25]:
model.predict(padded_x)

array([[0.51161015],
       [0.50008875],
       [0.5350828 ],
       [0.5331404 ],
       [0.5234462 ],
       [0.49435434],
       [0.50302386],
       [0.47839305],
       [0.47537407],
       [0.45912778]], dtype=float32)